[package]
name = "src"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"
ndarray = "0.15.6"
ndarray-rand = "0.14.0"
rand_distr = "0.4"

[lib]
crate-type = ["cdylib"]
name = "mlp"